#!/usr/bin/env bash
#
# This script is invoked after the createimg script copied the boot partition
# to the mounted image.
#
# The first argument is the type of odroid device, e.g. "c1" or "c2"
# The second argument is the folder of the mounted boot partition.
# The third argument is whether the rootfs is mounted read-only: "rw" or "ro"
#

