#!/usr/bin/env bash
set -e

# Enable root login using passwords
sed -i "s/PermitRootLogin without-password/PermitRootLogin yes/g" /etc/ssh/sshd_config

# Install the sshd_check_keys.service
systemctl enable /etc/systemd/system/sshd_check_keys.service

