#!/bin/bash
#
# This script overrides the make_resolv_conf() function in
# /sbin/dhclient-script and replaces /etc/resolv.conf with
# /tmp/resolv.conf

cur_make_resolv_conf=$(declare -f make_resolv_conf)
eval ${cur_make_resolv_conf//\/etc\/resolv.conf/\/tmp\/resolv.conf}

